name = "moemail"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
migrations_dir = "drizzle"
database_name = ""
database_id = ""
